apiVersion: v1
kind: Service
metadata:
  name: web-ngx
spec:
  type: NodePort
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: web-ngx
