version: '3'
services:
    vnc:
      image: final:v1
      ports:
        - ${vnc_port:-10999}:80
        - ${ssh_port:-20999}:22
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "4"
            #memory: 6144M
            #nofile: 
            #  soft: 64000
            #  hard: 65000
            #noproc: 65000
        #sysctls:
        #  - fs.file-max=65535
      volumes:
        - nfs-cptjack:/cptjack
      environment:
        - VNC_PASSWORD=${password:-123456}
        - RESOLUTION=1920x1080
        - TZ=Asia/Shanghai


volumes:
  nfs-cptjack:
    driver_opts:
      type: "nfs"
      o: "addr=lader,rw"
      device: ":/data/docker_data/${docker_name}"
